### PR TITLE
Fix non-existant pr or repo panic

### LINKED ISSUE #36: Panic when 404 pull request url
vot takaya oshibka valitsa:

> work:~ $ ash treetrunks/2 review 
12:02:24.63 [WARN] Stash returned error code: %d 404
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x48 pc=0x40f108]
> 
goroutine 1 [running]:
panic(0x82f700, 0xc82000e150)
        /usr/lib/go/src/runtime/panic.go:481 +0x3e6
main.review(0xc8200e7360, 0xc8203d3560, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/a.baranov/.go/src/github.com/seletskiy/ash/main.go:646 +0x1c8
main.reviewMode(0xc82043aa80, 0xc8200e72e0, 0x7fff28e57239, 0xa, 0xc8203d34a0, 0x2)
        /home/a.baranov/.go/src/github.com/seletskiy/ash/main.go:319 +0xcf7
main.main()
        /home/a.baranov/.go/src/github.com/seletskiy/ash/main.go:169 +0xe4bw

### PR DESCRIPTION
**Pull request by brnv**
Fix #36

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -643,6 +643,11 @@ func review(
 			review, err = pr.GetReview(path, ignoreWhitespaces)
 		}
 
+		if review == nil {
+			fmt.Println("Pull request not found")
```
Comment (kovetskiy) [inline main.go]: to stderr

Comment (brnv) [inline main.go]: done

**Comment by seletskiy** [comment]
@brnv, @kovetskiy: thx!
